<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-10-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
=======
# Generated by Django 3.2.4 on 2021-10-09 20:19
=======
# Generated by Django 3.2.7 on 2021-10-11 03:07
>>>>>>> 1441a2dc42f56eb3801242470177d738bd93d45f

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
=======
            name='OwnerFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatingUser', models.CharField(blank=True, default='', max_length=150)),
                ('AffectedUser', models.CharField(blank=True, default='', max_length=150)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('RunningBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('Note', models.CharField(max_length=500)),
>>>>>>> 1441a2dc42f56eb3801242470177d738bd93d45f
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ByRenter', models.BooleanField(default=True)),
                ('DepositingUser', models.CharField(blank=True, default='', max_length=150)),
                ('AffectedUser', models.CharField(blank=True, default='', max_length=150)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('RunningBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('Method', models.CharField(blank=True, choices=[('ETR', 'Electronic Transfer'), ('ECH', 'eCheck'), ('DBT', 'Debit Card')], default='DBT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('landlord_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('is_renter', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
>>>>>>> main
