# Generated by Django 3.2.7 on 2021-10-11 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatingUser', models.CharField(blank=True, default='', max_length=150)),
                ('AffectedUser', models.CharField(blank=True, default='', max_length=150)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('RunningBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('Note', models.CharField(max_length=500)),
            ],
        ),
    ]
