# Generated by Django 3.2.7 on 2021-10-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='payment',
            name='AffectedUser',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='DepositingUser',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
