# Generated by Django 3.2.4 on 2021-10-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
