# Generated by Django 3.2.8 on 2021-10-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapplication',
            name='resolved',
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='status',
            field=models.CharField(default='Open', max_length=15),
        ),
    ]
