# Generated by Django 3.2.8 on 2021-10-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0002_auto_20211010_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
