# Generated by Django 3.2.7 on 2021-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0002_rentalapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('is_renter', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
