# Generated by Django 3.2.7 on 2021-10-07 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0003_auto_20211006_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ByRenter', models.BooleanField(default=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('RunningBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Method', models.CharField(choices=[('ETR', 'Electronic Transfer'), ('ECH', 'eCheck'), ('DBT', 'Debit Card')], default='DBT', max_length=3)),
            ],
        ),
    ]
